import { Product, Salesman, DispatchSession, DamageLog } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'রূপচাঁদা সয়াবিন তেল (১ লিটার)',
    unit: 'পিস',
    unitPrice: 190,
    stock: 120,
    damageStock: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'ইস্পাহানি মির্জাপুর চা (২০০ গ্রাম)',
    unit: 'প্যাকেট',
    unitPrice: 130,
    stock: 85,
    damageStock: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'প্রাণ ম্যাঙ্গো জুস (২৫০ মিলি)',
    unit: 'পিস',
    unitPrice: 35,
    stock: 240,
    damageStock: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'তীর গম ও আটা (২ কেজি)',
    unit: 'ব্যাগ',
    unitPrice: 145,
    stock: 60,
    damageStock: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'ম্যাগি ২-মিনিট নুডলস (ফ্যামিলি প্যাক)',
    unit: 'প্যাক',
    unitPrice: 110,
    stock: 95,
    damageStock: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'হুইল ডিটারজেন্ট পাউডার (৫০০ গ্রাম)',
    unit: 'প্যাকেট',
    unitPrice: 65,
    stock: 150,
    damageStock: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'লাইফবয় টোটাল সাবান (১০০ গ্রাম)',
    unit: 'পিস',
    unitPrice: 40,
    stock: 180,
    damageStock: 0,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SALESMEN: Salesman[] = [
  {
    id: 'dsr-1',
    name: 'মোঃ রহিম উল্লাহ (ডিএসআর)',
    phone: '01712-345678',
    route: 'রুট ১: বাজার ও থানা রোড',
    currentDue: 1250,
  },
  {
    id: 'dsr-2',
    name: 'শফিকুল ইসলাম (ডিএসআর)',
    phone: '01819-876543',
    route: 'রুট ২: বাসস্ট্যান্ড ও কলেজ রোড',
    currentDue: 0,
  },
  {
    id: 'dsr-3',
    name: 'কামাল হোসেন (ডিএসআর)',
    phone: '01911-554433',
    route: 'রুট ৩: সদর ঘাট ও পুরান বাজার',
    currentDue: 500,
  },
];

export const INITIAL_DISPATCHES: DispatchSession[] = [
  {
    id: 'disp-sample-1',
    challanNo: 'CH-1001',
    salesmanId: 'dsr-1',
    salesmanName: 'মোঃ রহিম উল্লাহ (ডিএসআর)',
    salesmanRoute: 'রুট ১: বাজার ও থানা রোড',
    date: new Date().toISOString().split('T')[0],
    status: 'morning_issued',
    items: [
      {
        productId: 'prod-1',
        productName: 'রূপচাঁদা সয়াবিন তেল (১ লিটার)',
        unit: 'পিস',
        unitPrice: 190,
        issuedQty: 20,
        returnedQty: 0,
        damageReturnedQty: 0,
        soldQty: 0,
        totalAmount: 0,
      },
      {
        productId: 'prod-3',
        productName: 'প্রাণ ম্যাঙ্গো জুস (২৫০ মিলি)',
        unit: 'পিস',
        unitPrice: 35,
        issuedQty: 50,
        returnedQty: 0,
        damageReturnedQty: 0,
        soldQty: 0,
        totalAmount: 0,
      },
      {
        productId: 'prod-5',
        productName: 'ম্যাগি ২-মিনিট নুডলস (ফ্যামিলি প্যাক)',
        unit: 'প্যাক',
        unitPrice: 110,
        issuedQty: 15,
        returnedQty: 0,
        damageReturnedQty: 0,
        soldQty: 0,
        totalAmount: 0,
      },
    ],
    totalAmount: 0,
    cashCollected: 0,
    dueAmount: 0,
    notes: 'সকালের বাজার রুট চালান',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_DAMAGE_LOGS: DamageLog[] = [
  {
    id: 'dmg-1',
    productId: 'prod-1',
    productName: 'রূপচাঁদা সয়াবিন তেল (১ লিটার)',
    quantity: 1,
    action: 'returned_to_sellable',
    note: 'প্যাকেট সিল পরিবর্তন করে মূল স্টকে ফেরত',
    date: new Date().toISOString().split('T')[0],
  },
];
